#!/usr/bin/env python3

import sys
import subprocess
import argparse
from pathlib import Path
import re
from shutil import rmtree, copy
import os
import time
import hashlib

def cleanup(game_dir_patched):
    if game_dir_patched.exists():
        eldenring_path = game_dir_patched / "DarkSoulsIII.exe"
        while eldenring_path.exists():
            try:
                os.remove(eldenring_path)
                break
            except PermissionError:
                # DarkSoulsIII.exe is still running, retry in 3 s
                time.sleep(3)
            except Exception as e:
                print(f"ds3-patcher: could not delete {eldenring_path}: {e}")
                break
        rmtree(game_dir_patched)

def int_to_uint32_le_str(value):
    # Mask to 32 bits (wrap around if needed)
    wrapped = int(value) & 0xFFFFFFFF

    # 4‑byte little‑endian bytes object
    le_bytes = wrapped.to_bytes(4, byteorder="little", signed=False)

    # Convert each byte to two‑digit hex and concatenate
    return "".join(f"{b:02x}" for b in le_bytes)

if __name__ == "__main__":
    patcher_args = sys.argv[1:]

    parser = argparse.ArgumentParser(description="Patch Dark Souls 3 executable.")

    parser.add_argument("-g", "--gamepath", action='store', type=str, default=".", help="Path to game.")
    parser.add_argument("-p", "--permanent", action='store_true', help="Make the patches permanent.")
    parser.add_argument("-x", "--executable", action='store', type=str, default="", help="The executable to launch, relative to the games folder.")
    parser.add_argument("--all", action='store_true', help="Enable all options except rate adjustment and gamplay changes like `--disable-rune-loss`.")

    parser.add_argument("-s", "--skip-intro", action='store_true', help="Skip intro logos.")
    parser.add_argument("-res", "--resolution", action='store', type=str, default="", help="Skip intro logos.")
    parser.add_argument("-y", "--fix-camera", action='store_true', help="Disable camera reset.")

    patches = parser.parse_args(patcher_args)

    if "--" in sys.argv and not patches.permanent:
        patcher_args = sys.argv[1:sys.argv.index("--")]
    elif "--" in sys.argv and patches.permanent:
        print(f"\033[91mpermanent patch cannot be combined with temporary patches. Remove -p | --permanent or {sys.argv[sys.argv.index('--'):]}\033[m")
    elif "--" not in sys.argv and patches.permanent:
        pass
    else:
        exit("\033[91mYou did not specify if the patch is temporary or permanent\033[m")

    if patches.gamepath[-1] == "/" or patches.gamepath[-1] == "\\":
        patches.gamepath = patches.gamepath[:len(patches.gamepath)-1]

    if os.path.exists(f"{patches.gamepath}/DarkSoulsIII.exe"):
        game_dir = Path(patches.gamepath)
    elif os.path.exists("~/.local/share/Steam/steamapps/common/Dark Souls III/Game/DarkSoulsIII.exe"):
        game_dir = Path("~/.local/share/Steam/steamapps/common/Dark Souls III/Game/DarkSoulsIII.exe")
    elif os.path.exists("C:/Program Files/Steam/steamapps/common/Dark Souls III/Game/DarkSoulsIII.exe"):
        game_dir = Path("C:/Program Files/Steam/steamapps/common/Dark Souls III/Game/DarkSoulsIII.exe")
    elif os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Dark Souls III/Game/DarkSoulsIII.exe"):
        game_dir = Path("C:/Program Files (x86)/Steam/steamapps/common/Dark Souls III/Game/DarkSoulsIII.exe")
    else:
        exit("\033[91mCould not find DarkSoulsIII.exe\033[m")

    exe_hex = open(game_dir / "DarkSoulsIII.exe", "rb").read().hex()

    if hashlib.sha256(exe_hex.encode("utf-8")).hexdigest() != "dd314fa2638e728153081856c1b96d8f7442b88b1e70221407d13c9a730064cf":
        print("\033[91mWarning: DarkSoulsIII.exe is modified, this can lead to unexpected behavior\033[m")

    if patches.resolution != "":
        pattern = "80 07 00 00 38 04 00 00".replace(" ", "")
        #                            ^^ ^^ hab ich mir dazu gedacht, gucken ob es stimmt
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0]

            patches.resolution = patches.resolution.split("x")
            if patches.resolution[0] > 0 and patches.resolution[1] > 0:
                x = int_to_uint32_le_str(patches.resolution[0])
                y = int_to_uint32_le_str(patches.resolution[1])

                exe_hex = exe_hex[:addr] + x + y + exe_hex[addr + len(x + y):]
                print(f"\033[92m✓ ds3-patcher: resolution {patches.resolution[0]}x{patches.resolution[1]}\033[m")
            else:
                print("\033[91m✗ ds3-patcher: resolution must be greater than zero\033[m")
        else:
            print("\033[91m✗ ds3-patcher: resolution pattern scan failed\033[m")

    if patches.skip_intro or patches.all:
        pattern = "e8 1c ba fb ff 90 4d 8b c7 49 8b d4 48 8b c8 e8 0d ba fb ff".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 14
            patch = "48 31 c0 48 89 02 49 89 04 24 90 90 90 90 90 90 90 90 90 90".replace(" ", "")
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ ds3-patcher: skip intro\033[m")
        else:
            print("\033[91m✗ ds3-patcher: skip intro pattern scan failed\033[m")

    if patches.permanent:
        if os.path.exists(f"{game_dir}/DarkSoulsIII.exe") and not os.path.exists(f"{game_dir}/DarkSoulsIII.exe.bak"):
            copy(f"{game_dir}/DarkSoulsIII.exe", f"{game_dir}/DarkSoulsIII.exe.bak")
            print("DarkSoulsIII.exe backuped as DarkSoulsIII.exe.bak")
        exe = f"{game_dir}/DarkSoulsIII.exe"
        print("\033[92mEAC disabled, you cannot go online on official servers\033[m")

        # patch Dark Souls III
        open(exe, "wb").write(bytes.fromhex(exe_hex))
        del exe_hex

        exe = exe.replace("\\", "/")
        print(f"Patches permanently written to {os.path.join(exe)}")
    else:
        game_dir_patched = Path(f"{game_dir}/ds3-patcher-tmp/")

        # make sure a fresh directory is used
        cleanup(game_dir_patched)

        if not game_dir_patched.is_dir():
            game_dir_patched.mkdir()

        open(game_dir_patched / "DarkSoulsIII.exe", "wb").write(bytes.fromhex(exe_hex))

        del exe_hex

        # recreate game directory tree in game_dir_patched
        game_dirs = [d for d in game_dir.rglob("*") if d.is_dir()]
        for d in game_dirs:
            if d == game_dir_patched:
                continue
            if not (game_dir_patched / d).is_dir():
                (game_dir_patched / d).mkdir(parents=True)

        # hard link game files to game_dir_patched; symbolic links would be easier
        # to handle but by default windows 10 doesn't allow them
        game_files = [f for f in game_dir.rglob("*") if f.is_file()]
        for f in game_files:
            if f.name in ["DarkSoulsIII.exe", "ds3-patcher"]:
                continue
            if not (game_dir_patched / f).is_file():
                if sys.version_info.minor >= 10:
                    (game_dir_patched / f).hardlink_to(f)
                else:
                    f.link_to(game_dir_patched / f)

        # start patched exe directly to avoid EAC
        steam_cmd = sys.argv[1 + sys.argv.index("--"):]
        steam_cmd[-1] = Path(steam_cmd[-1]).parent.absolute() / game_dir_patched / ("DarkSoulsIII.exe" if patches.executable == "" else patches.executable)
        subprocess.run(steam_cmd, cwd=steam_cmd[-1].parent.absolute())

        # try to remove game_dir_patched
        cleanup(game_dir_patched)
